Zadanie 1 (4 pkt)

Wgraj zawartość pliku Zadanie_1.csv. Stwórz tablice w numpy w oparciu o wczytane dane.

Podaj:

a)	Ile komórek liczy sobie macierz

b)	Ile ma wierszy a ile kolumn

c)	Oblicz następujące statystyki opisowe dla macierzy: średnia/mediana/wariancja

d)	Powtórz czynność z podpunktu b), ale tym razem usuń z macierzy braki danych.


In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv('Zadanie_1.csv',sep=";")

In [7]:
dfnp = df.to_numpy()
print(dfnp.size) # a)
print(dfnp.shape) # b)
# c)
print("Srednia: "+str(np.mean(dfnp)))
print("Mediana: "+str(np.median(dfnp)))
print("Wariancja: "+str(np.var(dfnp)))
# ============
print()
# d)
dfnpnot = df.dropna().to_numpy()
print(dfnpnot.shape)
print("Srednia: "+str(np.mean(dfnpnot)))
print("Mediana: "+str(np.median(dfnpnot)))
print("Wariancja: "+str(np.var(dfnpnot)))
# ============

960
(60, 16)
Srednia: nan
Mediana: nan
Wariancja: nan

(43, 16)
Srednia: 332.2025610465116
Mediana: 34.0
Wariancja: 1042134.7488820893


Zadanie 2 (2 pkt)

Wgraj dane z pliku Zadanie_2.csv.

a)	Znajdź wektory własne, oraz wartości własne dla zawartej w pliku macierzy

b)	Oblicz macierz odwrotną dla macierzy z pliku



In [8]:
macierz = np.genfromtxt('Zadanie_2.csv', delimiter=';')
print(macierz)
# a)
print("Wektory wlasne: "+str(np.linalg.eig(macierz)))
print("Wartosci wlasne: "+str(np.linalg.eigvals(macierz)))
# =========

print("Macierz odwrotna: "+str(np.linalg.inv(macierz))) # b)

[[  1.   2.  15. -59.   9.   3.  75.   6.   7.   1.]
 [  0.   5.   0.   4.   6.  16.  44.   7.   1.   1.]
 [  7.  14.   3. -10.   9.  15.  73.   8.   2.   9.]
 [  1.   5.  15. -54.   5.  15.  35.   8.   6.   4.]
 [  0.   8.   5. -18.   7.  16.  91.   6.   7.   9.]
 [  7.  18.  23. -90.   4.   8.  31.   0.   1.   7.]
 [  2.   8.  20. -72.   4.   1.  91.   9.   4.   4.]
 [  4.  12.  18. -65.   6.   9.  76.   4.   9.   9.]
 [  7.  15.  13. -52.   5.   7.  54.   2.   7.   0.]
 [  2.   9.  15. -56.   6.   1.  98.   4.   8.   4.]]
Wektory wlasne: (array([104.34960192 +0.j        , -23.35660516+18.84992811j,
       -23.35660516-18.84992811j,  15.92989017 +0.j        ,
        -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
         0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
         3.87900166 +1.42651533j,   3.87900166 -1.42651533j]), array([[-0.29000475+0.j        , -0.07545445+0.07743149j,
        -0.07545445-0.07743149j, -0.03544485+0.j        ,
         0.42681634+0.j      

Zadanie 3 (4 pkt)

Wgraj dane z pliku Zadanie_3.csv
 
Gdzie A i B to wektory reprezentujące kolejne kolumny.

Aby stworzyć macierz podobieństwa w oparciu o macierz z pliku.

 



In [9]:
A = np.genfromtxt('Zadanie_3_macierz_A.csv', delimiter=',')
B = np.genfromtxt('Zadanie_3_macierz_B.csv', delimiter=',')
matrix = np.matmul((A / np.linalg.norm(A, axis=1, keepdims=True)), (B / np.linalg.norm(B, axis=1, keepdims=True)).T)
matrix

array([[0.7970534 , 0.93075784, 0.85152689, 0.80479273, 0.86772183],
       [0.3985267 , 0.56879646, 0.57428557, 0.32694705, 0.97618706],
       [0.92108283, 0.9763075 , 0.91890016, 0.9336035 , 0.69421013]])

Zadanie 4* (Nieobowiązkowe – 3 punkty dodatkowe) 

W pliku Zadanie_4.csv zawarte są dane o stanie dostępności gabinetu lekarskiego w danej minucie.

Napisz program, który przekształci dane w taki sposób, żeby w jednej linijce zapisany był początek i koniec przedziału czasowego, kiedy lekarz jest dostępny

Dane zapisz do pliku CSV.


In [10]:
import pandas as pd
# Nie jest to rozwiazanie do konca poprawne, bo brakuje jednej z dat dla lekarza
df = pd.read_csv('Zadanie_4.csv',sep=";").dropna(axis=1)
df['Date'] = df['DateTime'].apply(lambda x: x[:-6])
df['Time'] = df['DateTime'].apply(lambda x: x[-5:])
df2 = df.groupby(['Date','DoctorID','Type','City'],as_index=False).agg({'Time':['min','max']})
df2

Date DoctorID           Type    City   Time       
                                                 min    max
0  10.04.2020        4  Opthomologist  Krakow  13:20  13:34
1  16.03.2020        1             GP  Warsaw  12:00  14:01
2  16.03.2020        2             GP  Krakow  12:00  12:49
3  22.03.2020        3        Sugreon  Warsaw  08:01  09:06
4  29.03.2020        1             GP  Warsaw  14:00  14:37